### PR TITLE
Use android webkit MimeTypeMap instead of URLConnection

### PR DESCRIPTION
**Pull request by yunarta**
I found that MimeTypeMap offers more mime type than URLConnection.

### CODE REVIEW

**Comment by pavlospt** [comment]
Hello, @yunarta thank you for your PR! 

Two points: 
1) I know that the project does not have a .gitignore for `.idea` files, but could you please add one because your PR currently contains changes to those files as well :) 

2) I remember using it that way when I first wrote it, but something did not fit. Have you tested it with various file extensions?

**Comment by yunarta** [comment]
Hi

I've updated the pull request.

I also added test case by using data from https://android.googlesource.com/platform/frameworks/base/+/froyo/core/java/android/webkit/MimeTypeMap.java to check that URLConnection.guessContentTypeFromName does not have mime type that MimeTypeMap have.

**Comment by pavlospt** [comment]
Hey @yunarta , thanks for doing that! Although I have one objection, adding that test case inside the project will eventually lead to an unsynced state in case the MimeType list from Android AOSP gets updated! Also, adding such test, is like re-testing the AOSP code :) 

Can you please remove that test case? I am sure we can trust the AOSP code, for the MimeType! My previous comment was referring to live testing on files from a device :)

What do you think?

**Comment by yunarta** [comment]
They are actually gets updated, somehow i cannot get the actual MimeTypeMap from Robolectric :(
Was thinking of showing you the case where URLConnection.guessContentTypeFromName does not produce desired result.

We could modify theRxFile code in such way that we can choose the desired mime type map with parameter injection. What do you think?

**Comment by pavlospt** [comment]
Parameter injection sounds even better I think :) Could you try that solution so that we can evaluate on that? :)

**Comment by yunarta** [comment]
There you go

**Comment by pavlospt** [comment]
Great, that looks nice. One last thing: What do you think of converting those two `int`s into an `Enum` instead? :)

**Comment by yunarta** [comment]
Forgot to notify you, i did made the change to enum

**Comment by pavlospt** [comment]
@yunarta Perfect! Thank you for your contribution! Will merge it and prepare a release!

**Pull request merged**
